WorkoutWars.User = DS.Model.extend
  activities: DS.hasMany('activity', { embedded: 'load' }) 
  competitionJoins: DS.hasMany('competitionJoin', { embedded: 'load' }) 
  competitionActivities: DS.hasMany('competitionActivity', { embedded: 'load' }) 
  competitions: DS.hasMany('competition', { embedded: 'load' }) 
  name: DS.attr('string')
  nickname: DS.attr('string')
  email: DS.attr('string')
  gender: DS.attr('string')
  address: DS.attr('string')
  phone: DS.attr('string')
  weight: DS.attr('number')
  height: DS.attr('number')
  age: DS.attr('number')
  level: DS.attr('number')
  experience: DS.attr('number')
  nextLevelExperience: DS.attr('number')
  previousLevelExperience: DS.attr('number')
  canUpdate: DS.attr('boolean')
  canDelete: DS.attr('boolean')

 